// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7dKu4-CQKE4yO6au4DXFL96fcmxVboi0',
    appId: '1:225062013640:web:5642b591ffade64a5033fd',
    messagingSenderId: '225062013640',
    projectId: 'slowforet-996de',
    authDomain: 'slowforet-996de.firebaseapp.com',
    databaseURL: 'https://slowforet-996de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'slowforet-996de.appspot.com',
    measurementId: 'G-1PP5S5SS7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmvKcjE75fp9jzls3Uau9kFXnEBXCNqc',
    appId: '1:225062013640:android:66b89d4cb69a6eed5033fd',
    messagingSenderId: '225062013640',
    projectId: 'slowforet-996de',
    databaseURL: 'https://slowforet-996de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'slowforet-996de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYLnvMb4rAbWsTAX90SF-2Ie9tx4QOgkw',
    appId: '1:225062013640:ios:deb83729e73b9e5d5033fd',
    messagingSenderId: '225062013640',
    projectId: 'slowforet-996de',
    databaseURL: 'https://slowforet-996de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'slowforet-996de.appspot.com',
    androidClientId: '225062013640-n5bsvm120ps9j3skrkf465kbdkrljp9t.apps.googleusercontent.com',
    iosClientId: '225062013640-kb2913mct7p125t6dhiqnd9qlmsf61re.apps.googleusercontent.com',
    iosBundleId: 'com.SlowForet.slowforet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYLnvMb4rAbWsTAX90SF-2Ie9tx4QOgkw',
    appId: '1:225062013640:ios:00a0492ccae908f05033fd',
    messagingSenderId: '225062013640',
    projectId: 'slowforet-996de',
    databaseURL: 'https://slowforet-996de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'slowforet-996de.appspot.com',
    androidClientId: '225062013640-n5bsvm120ps9j3skrkf465kbdkrljp9t.apps.googleusercontent.com',
    iosClientId: '225062013640-eco918n2msnbjdo8q397m1qekp20il8l.apps.googleusercontent.com',
    iosBundleId: 'com.SlowForet.slowforet.RunnerTests',
  );
}
